extends:
  - stylelint-config-standard
  - stylelint-prettier/recommended

rules:
  selector-class-pattern: "^[a-z0-9_\\-]+$"
  font-family-no-missing-generic-family-keyword: null
  no-invalid-position-at-import-rule: null
  import-notation: "string"
  


 
 
